[package]
name = "xunhen-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
xunhen = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "patch"
path = "fuzz_targets/patch.rs"
test = false
doc = false
bench = false

[[bin]]
name = "records"
path = "fuzz_targets/records.rs"
test = false
doc = false
bench = false
